type: custom # Configurable charger
name: Generic
sample: |
  status: # charger status A..F
    source: ...
    # ...
  enabled: # charger enabled state (true/false or 0/1)
    source: ...
    # ...
  enable: # set charger enabled state
    source: ...
    # ...
  maxcurrent: # set charger max current
    source: ...
    # ...
